language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    repo: rhdtl78/rhdtl78.github.io
    branches:
      only:
        - master
